---
- name: Install supervisor
  pip:
    name: supervisor
    state: latest
    executable: /opt/anaconda3/bin/pip
    extra_args: --user
- name: Supervisor directory
  file:
    path: ~/supervisor
    state: directory
- name: Supervisor log directory
  file:
    path: ~/supervisor/log
    state: directory
- name: Supervisor config file for jobrun
  template:
    src: supervisord.conf.j2
    dest: ~/supervisor/supervisord.conf
- name: Kill any running supervisord
  command: killall supervisord
  ignore_errors: yes
- name: Wait for the supervisord processes to finish
  pause:
    seconds: 10
- name: Run supervisor
  command: ~/.local/bin/supervisord -c ~/supervisor/supervisord.conf -q ~/supervisor/log -l ~/supervisor/supervisor.log
